### ISSUE TITLE
Assignment Progress

### ISSUE THREAD

**Issue by dluman** [term-world/powerplant-solution#1]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Paperwork

- [ ] No TODO markers left in group-reflection.md
- [ ] No TODO markers left in any individual reflection

## Control Room

- [x] No TODO markers left in the main.py file

## Percent complete

Based on the checks achieved, this assignment is `33%` complete.
